### PR TITLE
Add default keyword values for main IIIF objects

### PR DESCRIPTION
**Pull request by giacomomarchioro**
This pull request add [the default keywords to the JSON shema](http://json-schema.org/understanding-json-schema/reference/generic.html) for the main IIIF object classes.

E.g. the default keyword for Manifest type is "Manifest".

The default keywords are useful for solving https://github.com/iiif-prezi/iiif-prezi3/issues/12.

### CODE REVIEW

**Comment by glenrobson** [comment]
Can we drop 3.6 in the test and add 3.10 which is the latest python version.

**Comment by glenrobson** [comment]
Glen to create a new pull request and let Giacomo know when its ready.

**Comment by glenrobson** [comment]
I've just been looking at something and came across a `const` keyword:

https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values

Would this be more suitable than `default`?

**Comment by giacomomarchioro** [comment]
> I've just been looking at something and came across a `const` keyword:
> 
> https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values
> 
> Would this be more suitable than `default`?

Yes,  it makes much more sense from the semantic point of view, however,  all my attempts using datamodel-codegen failed, maybe it is linked with this issue: https://github.com/koxudaxi/datamodel-code-generator/issues/658

**Comment by glenrobson** [comment]
Ah thats a shame. Oh well maybe we can change it to `const` when its supported. 

I've removed python 3.6 from the main branch so if you update the tests should work then and I can merge.

**Comment by glenrobson** [comment]
```
git checkout main
git pull origin 
git checkout defaulttypevalue
git merge main
git push
```

**Pull request merged**
